steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/proj2-298620/slack-bolt-weather:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/proj2-298620/slack-bolt-weather:$SHORT_SHA']
