steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/proj2-298620/slack-bolt-weather:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/proj2-298620/slack-bolt-weather:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'slack-bolt-weather', '--region=us-east1', '--platform=managed', '--image=gcr.io/proj2-298620/slack-bolt-weather:$SHORT_SHA']
